# Generated by Django 5.0.2 on 2024-03-03 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activation', '0003_alter_bankaccount_account_number_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='account_number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
