# Generated by Django 5.0.2 on 2024-03-03 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activation', '0004_alter_bankaccount_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='account_number',
            field=models.IntegerField(max_length=10, unique=True),
        ),
    ]
