# Generated by Django 5.0.2 on 2024-03-03 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activation', '0005_alter_bankaccount_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='account_number',
            field=models.IntegerField(blank=True, default='', max_length=50, null=True, unique=True),
        ),
    ]
