# Generated by Django 5.0.2 on 2024-03-03 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activation', '0006_alter_appuser_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='account_number',
            field=models.IntegerField(blank=True, default='', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='account_number',
            field=models.IntegerField(unique=True),
        ),
    ]
