# Generated by Django 5.0.2 on 2024-03-03 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activation', '0007_alter_appuser_account_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='account_number',
            field=models.CharField(blank=True, default='', max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='account_number',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
